services:
  grafana:
    user: root
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    volumes:
     - ./grafana/data:/var/lib/grafana
     - ./grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
    ports:
      - "3000:3000"
    networks:
     - universal
  
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
    networks:
      - universal


  # alert-manager:
  #   container_name: alert-manager
  #   image: bitnami/alertmanager
  #   restart: unless-stopped
  #   ports:
  #     - "9093:9093"
  #   volumes:
  #     - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  #     - alertmanager-data:/data


#1860 - node

volumes:
  prometheus-data:
  alertmanager-data:

networks:
  universal: