services:
  grafana:
    user: root
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    environment:
      - GF_SMTP_ENABLED=${GF_SMTP_ENABLED}
      - GF_SMTP_HOST=${GF_SMTP_HOST}
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_SKIP_VERIFY=${GF_SMTP_SKIP_VERIFY}
      - GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}
    volumes:
     - ./grafana/data:/var/lib/grafana
    # - ./grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
    ports:
      - "3000:3000"
    networks:
     - universal

  loki:
    container_name: loki
    image: grafana/loki
    ports: 
     - "3100:3100"
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
    networks:
      - universal

  prometheus:
    container_name: prometheus
    image: bitnami/prometheus
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - universal
volumes:
  prometheus-data:
  alertmanager-data:

networks:
  universal:
    name: monitoring