# prometheus/prometheus.yml

global:
  scrape_interval: 10s

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

rule_files:
- 'alerts.yml'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: 'node-exporter'
    static_configs:
      - targets: ["192.168.4.196:9100"]

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['192.168.4.196:9102']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.4.196:9101']